describe ('Verifikasi User Berhasil Login', () => {
  it('TC-LG-001 Login dengan Username valid dan Password valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Admin')
    cy.get('[name="password"]').type('admin123')
    cy.get('.oxd-button').click()
    cy.get('.oxd-alert').should('not.exist')
    cy.url({timeout: 10000}).should('include', 'dashboard')
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('be.visible')
    cy.get('.oxd-userdropdown-img').should('be.visible')
    cy.get('.oxd-userdropdown-name').should('be.visible')
  })
})

describe ('Verifikasi User Gagal Login', () => {
  it('TC-LG-002 Login dengan Username dan Password kosong', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('.oxd-button').click()
    cy.get('.oxd-input--error').should('exist')
    cy.get('.oxd-input-field-error-message').should('exist')
    cy.url().should('include', 'login')
  })
  it('TC-LG-003 Login dengan Username valid dan Password kosong', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Admin')
    cy.get('.oxd-button').click()
    cy.get('.oxd-input--error').should('exist')
    cy.get('.oxd-input-field-error-message').should('exist')
    cy.url().should('include', 'login')
  })
  it('TC-LG-004 Login dengan Username kosong dan Password valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="password"]').type('admin123')
    cy.get('.oxd-button').click()
    cy.get('.oxd-input--error').should('exist')
    cy.get('.oxd-input-field-error-message').should('exist')
    cy.url().should('include', 'login')
  })
  it('TC-LG-005 Login dengan Username tidak valid dan Password valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Agus@998')
    cy.get('[name="password"]').type('admin123')
    cy.get('.oxd-button').click()
    cy.get('.oxd-alert').should('be.visible').and('contain.text', 'Invalid credentials')
    cy.url().should('include', 'login')
  })
  it('TC-LG-006 Login dengan Username valid dan Password tidak valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Admin')
    cy.get('[name="password"]').type('Agus@998')
    cy.get('.oxd-button').click()
    cy.get('.oxd-alert').should('be.visible').and('contain.text', 'Invalid credentials')
    cy.url().should('include', 'login')
  })
  it('TC-LG-007 Login dengan Username tidak valid dan Password tidak valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Agus@998')
    cy.get('[name="password"]').type('admin998')
    cy.get('.oxd-button').click()
    cy.get('.oxd-alert').should('be.visible').and('contain.text', 'Invalid credentials')
    cy.url().should('include', 'login')
  })
})

describe ('Verifikasi Forgot Password', () => {
  it('TC-LG-008 Text Link Forgot Password mengarahkan ke halaman Reset Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('.orangehrm-login-forgot > .oxd-text').click()
    cy.get('.oxd-text--h6').should('be.visible')
    cy.url().should('include', 'Reset')
  })
  it('TC-LG-009 Reset password tanpa mengisi username', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('.orangehrm-login-forgot > .oxd-text').click()
    cy.get('.oxd-text--h6').should('be.visible')
    cy.url().should('include', 'Reset')
    cy.get('.oxd-button--secondary').click()
    cy.get('.oxd-input--error').should('exist')
    cy.get('.oxd-input-group > .oxd-text').should('exist')
    cy.url().should('include', 'Reset')
  })
  it('TC-LG-010 Reset password dengan username valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('.orangehrm-login-forgot > .oxd-text').click()
    cy.get('.oxd-text--h6').should('be.visible')
    cy.url().should('include', 'Reset')
    cy.get('[name="username"]').type('Admin')
    cy.get('.oxd-button--secondary').click()
  })
})

describe ('Verifikasi Password Security dan Login Session', () => {
  it('TC-LG-011 Verifikasi Password terenkripsi pada field Password', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="password"]').type('admin123')
    cy.get('[name="password"]').should('have.attr', 'type', 'password')
  })
  it('TC-LG-012 Verifikasi Akses halaman Dashboard sesudah menekan tombol back dan forward browser', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Admin')
    cy.get('[name="password"]').type('admin123')
    cy.get('.oxd-button').click()
    cy.get('.oxd-alert').should('not.exist')
    cy.url({timeout: 10000}).should('include', 'dashboard')
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('be.visible')
    cy.get('.oxd-userdropdown-img').should('be.visible')
    cy.get('.oxd-userdropdown-name').should('be.visible')
    cy.go('back')
    cy.go('forward')
    cy.url().should('include', 'dashboard')
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('be.visible')
    cy.get('.oxd-userdropdown-img').should('be.visible')
    cy.get('.oxd-userdropdown-name').should('be.visible')
    cy.reload()
    cy.url({timeout: 10000}).should('include', 'dashboard')
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('be.visible')
    cy.get('.oxd-userdropdown-img').should('be.visible')
    cy.get('.oxd-userdropdown-name').should('be.visible')
  })
})