describe ('Verifikasi User Berhasil Login', () => {
  it('TC-LG-001 Login dengan Username valid dan Password valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Admin')
    cy.get('[name="password"]').type('admin123')
    cy.get('.oxd-button').click()
    cy.url({timeout: 10000}).should('include', 'dashboard')
    cy.get('.oxd-topbar-header-breadcrumb > .oxd-text').should('be.visible')
  })
})

describe ('Verifikasi User Gagal Login', () => {
  it('TC-LG-002 Login dengan Username dan Password kosong', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('.oxd-button').click()
    cy.get('.oxd-input--error').should('exist')
    cy.get('.oxd-input-field-error-message').should('exist')
    cy.url().should('include', 'login')
  })
  it('TC-LG-003 Login dengan Username valid dan Password kosong', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Admin')
    cy.get('.oxd-button').click()
    cy.get('.oxd-input--error').should('exist')
    cy.get('.oxd-input-field-error-message').should('exist')
    cy.url().should('include', 'login')
  })
  it('TC-LG-004 Login dengan Username kosong dan Password valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="password"]').type('admin123')
    cy.get('.oxd-button').click()
    cy.get('.oxd-input--error').should('exist')
    cy.get('.oxd-input-field-error-message').should('exist')
    cy.url().should('include', 'login')
  })
  it('TC-LG-005 Login dengan Username tidak valid dan Password valid', () => {
    cy.visit('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login')
    cy.get('.oxd-text--h5').should('be.visible')
    cy.get('[name="username"]').type('Agus@998')
    cy.get('[name="password"]').type('admin123')
    cy.get('.oxd-button').click()
    cy.get('.oxd-alert').should('be.visible')
    cy.url().should('include', 'login')
  })
})